import {
  Loader2,
  ChevronLeft,
  HandCoins,
  CircleDotDashed,
  Inbox,
  Users,
  Check,
  Edit2,
  Trash2,
  Sun,
  Moon,
  Computer,
  Plus,
  ArrowRight,
  AlignJustify,
  X,
} from "lucide-react";

export const Icons = {
  chevronLeft: ChevronLeft,
  spinner: Loader2,
  collected: HandCoins,
  pending: CircleDotDashed,
  inbox: Inbox,
  customers: Users,
  check: Check,
  pen: Edit2,
  trashcan: Trash2,
  sun: Sun,
  moon: Moon,
  system: Computer,
  add: Plus,
  arrowRight: ArrowRight,
  hamburger: AlignJustify,
  close: X,
};
